class YouTubeFacade{constructor(){this.apiLoaded=!1;this.loadYouTubeAPI()}
loadYouTubeAPI(){if(!this.apiLoaded){const script=document.createElement('script');script.src='https://www.youtube.com/iframe_api';script.onload=()=>{this.apiLoaded=!0};document.body.appendChild(script)}}
createPlaylistEmbed(containerId,playlistId,options={}){const container=document.getElementById(containerId);if(!container){console.error(`Container with ID "${containerId}" not found.`);return}
container.innerHTML='';const iframe=document.createElement('iframe');iframe.width=options.width||'720';iframe.height=options.height||'405';iframe.src=`https://www.youtube.com/embed/videoseries?list=${playlistId}&autoplay=${options.autoplay || 0}`;iframe.frameBorder='0';iframe.allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture';iframe.allowFullscreen=!0;container.appendChild(iframe)}}
const youtubeFacade=new YouTubeFacade();const htmlContent=`
  <div style=display:flex;flex-direction:column;align-items:center;justify-content:center><p class=call-to-action style=text-align:center>💡 LIKE, COMMENT, and SUBSCRIBE for more helpful tutorials!</p><a class=subscribe-link href="https://www.youtube.com/channel/UCA3iM2B4lV7pLfNBUWL5DyA?sub_confirmation=1"style=margin-bottom:20px;text-align:center>📲 Subscribe to our channel for more tutorials | اشترك في القناة لمزيد من الدروس</a><div style=margin-bottom:20px;min-height:450px;background:#f3f3f3;display:flex;align-items:center;justify-content:center data-playlist-id=PLR24_qg5_8ibSbIfq5JuO3PZcjlTUi6fW id=playlist-1><div class=loader></div></div><div style=min-height:450px;background:#f3f3f3;display:flex;align-items:center;justify-content:center data-playlist-id=PLR24_qg5_8ib8v6YB3sKX9CAaIKoC20I9 id=playlist-2><div class=loader></div></div></div>`;const style=document.createElement('style');style.textContent=` .loader { border: 6px solid #f3f3f3; border-top: 6px solid #3498db; border-radius: 50%; width: 50px; height: 50px; animation: spin 1s linear infinite; } @keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } }`;document.head.appendChild(style);document.addEventListener('DOMContentLoaded',function(){const app=document.getElementById('app');if(app){app.innerHTML=htmlContent;const observer=new IntersectionObserver((entries)=>{entries.forEach(entry=>{if(entry.isIntersecting){const container=entry.target;const playlistId=container.getAttribute('data-playlist-id');const containerId=container.id;youtubeFacade.createPlaylistEmbed(containerId,playlistId);observer.unobserve(container)}})},{threshold:0.4});document.querySelectorAll('[data-playlist-id]').forEach((element)=>{observer.observe(element)})}});document.addEventListener('DOMContentLoaded',function(){const switchButtons=document.querySelectorAll('.switch-button');const facades=document.querySelectorAll('.video-facade');let activeIframe=null;switchButtons.forEach(function(button){button.addEventListener('click',function(){const selectedServer=button.getAttribute('data-server');if(activeIframe){activeIframe.parentElement.innerHTML=activeIframe.parentElement.dataset.originalContent;activeIframe=null}
switchButtons.forEach(btn=>btn.classList.remove('active'));button.classList.add('active');facades.forEach(facade=>{if(facade.classList.contains(`${selectedServer}-facade`)){facade.style.display='block'}else{facade.style.display='none'}})})});facades.forEach(function(facade){facade.dataset.originalContent=facade.innerHTML;facade.addEventListener('click',function(){const embedCode=facade.getAttribute('data-embed');const platform=facade.getAttribute('data-platform');if(activeIframe){activeIframe.parentElement.innerHTML=activeIframe.parentElement.dataset.originalContent;activeIframe=null}
let iframe=document.createElement('iframe');if(platform==='youtube'){iframe.src=`https://www.youtube.com/embed/${embedCode}?autoplay=1`}
iframe.width='100%';iframe.height='405';iframe.allow='autoplay; encrypted-media';iframe.frameBorder='0';facade.innerHTML='';facade.appendChild(iframe);activeIframe=iframe})})})
