document.getElementById("loading-message").style.display="none";const socialLinks=["https://www.facebook.com/matrixegybest1/","https://x.com/MatrixEgyFRP","https://www.instagram.com/matrix_egy/","https://www.youtube.com/@MxEgyFRP","https://mxegytech.rf.gd/expert-mobile-and-computer-repair-services/","https://mxegytech.rf.gd/frp-bypass-google-account-solution/","https://mxegytech.rf.gd/top-free-mobile-repair-tools/","https://mxegytech.rf.gd/topics/free-mobile-repair-guides-for-mobile-services/","https://mxegytech.rf.gd/topics/free-unlocking-tools-for-pc-and-mobile-services/","https://mxegytech.rf.gd/"];function getRandomSocialLink(){const randomIndex=Math.floor(Math.random()*socialLinks.length);return socialLinks[randomIndex]}
const buttons=document.querySelectorAll("#start-button");buttons.forEach(button=>{button.addEventListener("click",function(event){const randomLink=getRandomSocialLink();window.open(randomLink,"_blank")})});const animationContainer=document.getElementById("animation-container");let animation=lottie.loadAnimation({container:animationContainer,renderer:"svg",loop:!0,autoplay:!0,path:"https://lottie.host/61b56efa-48fb-448f-b061-b8e5de76be22/VK5hZN0Fua.json"});const messages=["📥 جاري فحص وتحضير الروابط، يرجى الانتظار...","🔄 Preparing your download links, please wait..."];let messageIndex=0;let messageInterval;const finalMessages=["✔️ تم فحص وتحضير الروابط بنجاح بالاسفل. يمكنك الآن التحميل!","✔️ The links have been successfully checked and prepared. You can now download!"];let finalMessageIndex=0;function startMessageRotation(){messageInterval=setInterval(()=>{messageIndex=(messageIndex+1)%messages.length;document.getElementById("loading-message").textContent=messages[messageIndex]},3000)}
function startFinalMessageRotation(){setInterval(()=>{finalMessageIndex=(finalMessageIndex+1)%finalMessages.length;document.getElementById("loading-message").textContent=finalMessages[finalMessageIndex]},3000)}
const timerElement=document.getElementById("timer");const linksContent=document.getElementById("links-content");const startButton=document.getElementById("start-button");let countdown=60;let countdownInterval;let paused=!1;function updateTimerDisplay(){let countdownText=`${countdown} ثانية`;if(countdown%2===0){countdownText=`${countdown} Second`}
timerElement.textContent=countdownText}
function startTimer(){countdownInterval=setInterval(()=>{if(!paused){countdown-=1;updateTimerDisplay();if(countdown<=0){clearInterval(countdownInterval);timerElement.style.display="none";linksContent.style.display="block";animation.destroy();animation=lottie.loadAnimation({container:animationContainer,renderer:"svg",loop:!1,autoplay:!0,path:"https://lottie.host/c11dbcb8-4618-4040-870e-2fbb448f1ebf/PEZycEzXgA.json"});clearInterval(messageInterval);startFinalMessageRotation();linksContent.scrollIntoView({behavior:"smooth"});const supportMessage=`
               <div class="wp-block-buttons" style="display:flex;justify-content:center;gap:10px;align-items:center"><div class="wp-block-button has-custom-font-size has-medium-font-size"><a class="wp-block-button__link has-neve-link-hover-color-background-color has-background wp-element-button" href="https://www.facebook.com/matrixegybest1/" target="_blank" rel="noopener noreferrer" style="border-style:none;border-width:0;border-radius:32px;padding:var(--wp--preset--spacing--20)">facebook</a></div><div class="wp-block-button has-custom-font-size has-medium-font-size"><a class="wp-block-button__link has-nv-c-1-background-color has-background wp-element-button" href="http://mxegytech.rf.gd" target="_blank" rel="noopener noreferrer" style="border-style:none;border-width:0;border-radius:32px;padding:var(--wp--preset--spacing--20)">website</a></div><div class="wp-block-button has-custom-font-size has-medium-font-size"><a class="wp-block-button__link has-nv-c-2-background-color has-background wp-element-button" href="https://www.youtube.com/@MxEgyFRP" target="_blank" rel="noopener noreferrer" style="border-radius:33px;padding:var(--wp--preset--spacing--20)">youtube</a></div><div class="wp-block-button has-custom-font-size has-medium-font-size"><a href="https://buymeacoffee.com/mustaphaquraa" target="_blank" rel="noopener noreferrer"><img loading="lazy" decoding="async" src="https://cdn.buymeacoffee.com/buttons/v2/default-yellow.png" alt="Buy Me A Coffee" width="200" height="50" style="border-radius:32px"></a></div></div>
                `;linksContent.insertAdjacentHTML("beforebegin",supportMessage)}}},1000)}
document.addEventListener('visibilitychange',function(){paused=document.hidden});async function fetchLinks(){try{const response=await fetch('https://matrixegy.github.io/postjf/new.json');const data=await response.json();const postId=getQueryParam("post_id");if(postId&&data[postId]){let linksHTML="<ul>";data[postId].forEach(link=>{linksHTML+=`<li><a href="${link.url}" target="_blank">${link.name}</a></li>`});linksHTML+="</ul>";linksContent.innerHTML=linksHTML}else{linksContent.innerHTML="<p>لم يتم العثور على روابط لهذه المقالة.</p>"}}catch(error){console.error("Error fetching links:",error);linksContent.innerHTML="<p>⚠️ عذرًا، حدث خطأ أثناء تحميل الروابط. يرجى المحاولة لاحقًا.</p>"}}
function getQueryParam(param){const urlParams=new URLSearchParams(window.location.search);return urlParams.get(param)}
document.addEventListener("DOMContentLoaded",function(){startMessageRotation();fetchLinks()});startButton.addEventListener("click",function(){startButton.style.display="none";document.getElementById("pre-start-message").style.display="none";updateTimerDisplay();startTimer();document.getElementById("loading-message").style.display="block";animation.destroy();animationContainer.style.width="250px";animationContainer.style.height="250px";animation=lottie.loadAnimation({container:animationContainer,renderer:"svg",loop:!0,autoplay:!0,path:"https://lottie.host/61ee45f9-a98c-4a40-bebc-ad3939c142ba/VKcaLOW6JV.json"});startMessageRotation()})
